### ISSUE TITLE
GameAnalytics.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x85

### ISSUE THREAD

**Issue by Liimurr** [GameAnalytics/GA-SDK-UNREAL#11]
get a build error: Plugins\GameAnalytics\Source\ThirdParty\GA-SDK-CPP\lib\Win64\GameAnalytics.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x85

what I've tried:
switching to the msvc toolchain used to compile the lib (14.38)

checking with dumpbin:
```
>dumpbin /SYMBOLS GameAnalytics.lib
Microsoft (R) COFF/PE Dumper Version 14.38.33141.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file GameAnalytics.lib
GameAnalytics.lib : warning LNK4048: Invalid format file; ignored

  Summary
  ```
  
  not sure if I'm just being obtuse, if so apologies in advance.

backporting changes for UE 4.26:  
GamAnalyticsProvider.h
```
  #if UE_VERSION_NEWER_THAN(5,0,-1)
    virtual void SetDefaultEventAttributes(TArray<FAnalyticsEventAttribute>&& Attributes) override;
    virtual TArray<FAnalyticsEventAttribute> GetDefaultEventAttributesSafe() const override;
    virtual int32 GetDefaultEventAttributeCount() const override;
    virtual FAnalyticsEventAttribute GetDefaultEventAttribute(int AttributeIndex) const override;
#endif
```
GameAnalyticsProvider.cpp
```
#if UE_VERSION_NEWER_THAN(5,0,-1)
void FAnalyticsProviderGameAnalytics::SetDefaultEventAttributes(TArray<FAnalyticsEventAttribute>&& Attributes)
{
}

TArray<FAnalyticsEventAttribute> FAnalyticsProviderGameAnalytics::GetDefaultEventAttributesSafe() const
{
    return {};
}

int32 FAnalyticsProviderGameAnalytics::GetDefaultEventAttributeCount() const
{
    return 0;
}

FAnalyticsEventAttribute FAnalyticsProviderGameAnalytics::GetDefaultEventAttribute(int AttributeIndex) const
{
    return FAnalyticsEventAttribute();
}
#endif
```

GameAnalyticsTargetSettingsCustomization.cpp
```
#if UE_VERSION_OLDER_THAN(5, 0, 0)
  #define UE UE4
#endif
```
  
engine version: UE 4.26 
toolchain version: 14.38.33141
Windos SDK: 10.0.18362.0

**Comment by dorin-ga** [comment]
Looks like you haven't checked out the binaries. GameAnalytics binaries are stored using [git-lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage). After cloning the repository you will have to pull the libraries using git-lfs in order for the plugin to work.
