### ISSUE TITLE
Plugin is not compatible for 5.4

### ISSUE THREAD

**Issue by bluebubblebee** [GameAnalytics/GA-SDK-UNREAL#4]
In UE 5.4 there is a compiler error on UEGameAnalytics.cpp in the StartupModule
It looks like the FAnalyticsProviderGameAnalytics needs some parameters
GameAnalyticsProvider = MakeShareable((new FAnalyticsProviderGameAnalytics());

**Comment by dorin-ga** [comment]
Hello, we have built and tested the latest plugin version using Unreal Engine 5.4.2 and it seems to work correctly in our tests. Moreover the constructor for `FAnalyticsProviderGameAnalytics` requires no parameters: https://github.com/GameAnalytics/GA-SDK-UNREAL/blob/016817501168b4002b14a106fee852ff4277f4a0/GameAnalytics/Source/GameAnalytics/Private/UEGameAnalytics.cpp#L199

Could you please post the whole error message here so we can investigate? Did you download the plugin from github or from the Unreal Marketplace?

**Comment by bluebubblebee** [comment]
Thank you,
I tried with the market place version for 5.3 as the 5.4 wasn't available just yet. 

The error that I got is:
UEGameAnalytics.cpp Line: 27 -	no instance of overloaded function "MakeShareable" matches the argument list		

UEGameAnalytics.cpp Line: 27 -	object of abstract class type "FAnalyticsProviderGameAnalytics" is not allowed:			
pure virtual function "IAnalyticsProvider::SetDefaultEventAttributes" has no overrider
            pure virtual function "IAnalyticsProvider::GetDefaultEventAttributesSafe" has no overrider
            pure virtual function "IAnalyticsProvider::GetDefaultEventAttributeCount" has no overrider
            pure virtual function "IAnalyticsProvider::GetDefaultEventAttribute" has no overrider

**Comment by dorin-ga** [comment]
I see, seems to be a problem with the marketplace version as those are already defined in the SDK, e.g:
https://github.com/GameAnalytics/GA-SDK-UNREAL/blob/016817501168b4002b14a106fee852ff4277f4a0/GameAnalytics/Source/GameAnalytics/Private/UEGameAnalytics.cpp#L221

Let us take a look and we'll fix the marketplace version.
