### ISSUE TITLE
Fix Undefined Behavior caused by misaligned classes.

### ISSUE THREAD

**Issue by AndreaCatania** [GameAnalytics/GA-SDK-UNREAL#6]
Hello, in unreal engine you have to wrap any non unreal engine C++ header (like https://github.com/GameAnalytics/GA-SDK-UNREAL/blob/master/GameAnalytics/Source/GameAnalytics/Public/GameAnalytics.h#L10-L12) around `PRAGMA_PUSH_PLATFORM_DEFAULT_PACKING` and `PRAGMA_POP_PLATFORM_DEFAULT_PACKING` to avoid importing the classes with wrong alignment.

For legacy reasons unreal engine changes the default class alignment for any imported class, even the C++ standard classes. This causes the ABI to break between the classes you include in unreal engine and the actual compiled binaries.
To fix this you can disable this alignment by using the specified macro, and below you can see an example.

Example code:
```
PRAGMA_PUSH_PLATFORM_DEFAULT_PACKING
#include <string>
#include <vector>
#include <stdint.h>
PRAGMA_POP_PLATFORM_DEFAULT_PACKING
```

**Comment by AndreaCatania** [comment]
You can read more about this in the UE documentation here: https://dev.epicgames.com/documentation/en-us/unreal-engine/third-party-libraries?application_version=4.27

**Comment by dorin-ga** [comment]
Hello, thank you for reporting this issue. We have released a patch that should address this.

**Comment by dorin-ga** [comment]
Hello, thank you for reporting this issue. We have released a patch that will address this.
